version: '3'

services:
  frontend-web:
    build:
      context: RIMA-Frontend
      dockerfile: Dockerfile-dev
    image: rima-frontend
    stdin_open: true
    volumes:
    - npm-cache:/root/.npm
    restart: "no"

  backend-api:
    image: rima-backend
    ports:
    - 8000:8080
    environment:
    - PRELOAD_MODELS="false"
    restart: "no"

  backend-worker:
    image: rima-backend
    environment:
    - PRELOAD_MODELS="false"
    restart: "no"

  model-downloader:
    image: rima-model-downloader
    restart: "no"
    volumes:
    - ./tmp/download:/tmp

  model-server:
    image: rima-model-server
    ports:
    - 8001:8080
    restart: "no"

volumes:
  npm-cache:
    external: false
